version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "RenewalExtractPolicyModificationApproval"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1gb1ikk84srhc"
s3_prefix = "RenewalExtractPolicyModificationApproval"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
