module.exports = {
    RENEWAL_VAULT: "renewal_vault",
    RENEWAL_VAULT_AUDIT: "renewal_vault_audit",
    RENEWAL_VAULT_HISTORY: "renewal_vault_history",
    RENEWAL_VAULT_JOB_SCHEDULE: "renewal_vault_job_schedule",
    RENEWAL_VAULT_LOG: "renewal_vault_log",
    RENEWAL_VAULT_SUMMARY: "renewal_vault_summary",
    RENEWAL_VAULT_GCV: "renewal_vault_gcv",
    RENEWAL_VAULT_PCV: "renewal_vault_pcv",
    RENEWAL_VAULT_MISCD: "renewal_vault_miscd",
    RENEWAL_VAULT_GCV_HISTORY: "renewal_vault_gcv_history",
    RENEWAL_VAULT_PCV_HISTORY: "renewal_vault_pcv_history",
    RENEWAL_VAULT_MISCD_HISTORY: "renewal_vault_miscd_history",
    RENEWAL_EXTRACT_MODIFICATION: "renewal_extract_modification",
};